### ISSUE TITLE
US 03.02.01 SP: 5 Geolocation Tracking

### ISSUE THREAD

**Issue by djschroeder** [CMPUT301W24T33/SyntaxTerror#21]
US 03.02.01 As a user, I want the option to enable or disable geolocation tracking for event verification.

- [x] user can enable/disable geolocation tracking

**Comment by reecemlrking** [comment]
Currently user can choose to give location permission when checking into an event. User should 

- [ ] have the option to enable/disable geolocation tracking app-wide
- [ ] not have to have geolocation enabled unless the event restricts access to location
